version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: sketch_history_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: sketch_history
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app", "-d", "sketch_history"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sketch_history_backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://app:app@db:5432/sketch_history
      # CORS not needed when proxied via frontend Nginx, but keep for safety
      CORS_ORIGINS: http://localhost,http://127.0.0.1
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Frontend will call backend via Nginx proxy at /api
        VITE_API_URL: /api
    container_name: sketch_history_frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  pgdata:
    driver: local